"""Generate a large synthetic chat-log corpus.

For each FAQ we synthesise N realistic patient sessions:

   user  : a paraphrase of the FAQ question (synonyms, prefixes,
           filler words, occasional typo)
   bot   : the FAQ answer
   user  : an organic follow-up drawn from a small template bank
   bot   : a one-line follow-up answer

Every paraphrase is generated by combining:
  - prefix banks (politeness, hedging, urgency)
  - synonym swaps from a curated medical lexicon
  - light surface noise (case, punctuation, single typo)
  - optional Roman-Urdu sprinkles (mera/aap, dard, ho raha hai, …)

We bound the corpus size by total bytes — not by record count — so
the user's "~10 MB" budget is honoured without inflating noise.

Run:  python data/synth_chat_logs.py --bytes 5_000_000
"""
from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
from pathlib import Path

HERE = Path(__file__).parent


# ---------------- paraphrase machinery ----------------


PREFIX_BANK = [
    "", "", "", "",  # empty cases weighted heavily
    "can you tell me ", "could you tell me ", "i want to know ",
    "i need to know ", "please tell me ", "kindly explain ",
    "do you know ", "i was wondering ", "could you explain ",
    "tell me ", "explain ", "what about this — ",
    "quick question, ", "one more thing, ",
]

SUFFIX_BANK = [
    "", "", "", "?", " ?", " please", " kindly", " thanks",
    " thanks in advance", "...", " plz",
]

URDU_SPRINKLES = [
    "", "", "", "", "",  # mostly clean
    " (urdu: dard hai)", " — dard horaha hai",
    " mera bhai pooch raha hai", " aap bata sakte hain",
    " thori si tension hai", " thori si khansi bhi hai",
]

SYNONYM_MAP = {
    "mri": ["scan", "imaging"],
    "ct": ["computed tomography", "ct scan"],
    "x-ray": ["xray", "radiograph"],
    "scan": ["imaging", "test"],
    "doctor": ["physician", "clinician", "dr"],
    "physiotherapist": ["physio", "therapist"],
    "cardiologist": ["heart specialist"],
    "medicine": ["medication", "meds", "tablet"],
    "bp": ["blood pressure", "hypertension"],
    "blood pressure": ["bp", "hypertension"],
    "chest pain": ["chest discomfort", "tight chest", "pressure in my chest"],
    "knee pain": ["sore knee", "achy knee"],
    "back pain": ["sore back", "lower back ache"],
    "exercise": ["workout", "activity", "training"],
    "stretch": ["stretching", "loosen"],
    "fast": ["skip food", "avoid eating"],
    "before": ["prior to", "ahead of"],
    "after": ["following", "post"],
    "what is": ["explain", "tell me about", "define"],
    "how long": ["what is the duration of", "how much time for"],
    "do i need to": ["should i", "is it required to"],
    "can i": ["is it okay to", "am i allowed to"],
    "should i": ["do i need to", "is it advisable to"],
    "how often": ["frequency of", "how many times"],
}

FOLLOWUP_TEMPLATES = [
    "also what about water?",
    "and how often?",
    "is it serious?",
    "should i be worried?",
    "any side effects?",
    "is it safe for kids?",
    "what if it gets worse?",
    "is there a home remedy?",
    "can i drive after that?",
    "is it expensive?",
    "how soon should i come back?",
    "thanks, just one more — is it safe in pregnancy?",
    "okay, and what should i avoid?",
    "and what about salt?",
    "what if i forget once?",
    "is it okay during ramadan?",
]

FOLLOWUP_BOT_LINES = [
    "Good follow-up — please discuss the specifics with your clinician at the next visit.",
    "We address that on the FAQ page; ask if you want details.",
    "Most patients tolerate this well; tell us if anything new appears.",
    "Side effects are usually mild and short-lived — we monitor closely.",
    "It is generally safe but please review with your physician for your case.",
    "Children may need a different dose or protocol — ask the paediatric team.",
    "If symptoms worsen, please contact the clinic or emergency line.",
    "Take it at the same time each day for consistency.",
    "Driving is usually fine unless you were given a sedative.",
    "Most of the work is included in your normal appointment fee.",
]


def _swap_chars(s: str, rng: random.Random) -> str:
    chars = list(s)
    pos = [i for i in range(len(chars) - 1)
           if chars[i].isalpha() and chars[i + 1].isalpha()]
    if not pos:
        return s
    i = rng.choice(pos)
    chars[i], chars[i + 1] = chars[i + 1], chars[i]
    return "".join(chars)


def _phrase_swap(text: str, rng: random.Random) -> str:
    t = text.lower()
    for k, alts in SYNONYM_MAP.items():
        if " " in k and k in t and rng.random() < 0.55:
            return t.replace(k, rng.choice(alts), 1)
    return text


def _word_swap(text: str, rng: random.Random) -> str:
    toks = re.findall(r"\w+|\W+", text)
    out = []
    for t in toks:
        key = t.lower()
        if key in SYNONYM_MAP and rng.random() < 0.6:
            out.append(rng.choice(SYNONYM_MAP[key]))
        else:
            out.append(t)
    return "".join(out)


def paraphrase(question: str, rng: random.Random) -> str:
    q = _phrase_swap(question, rng)
    q = _word_swap(q, rng)
    pre = rng.choice(PREFIX_BANK)
    suf = rng.choice(SUFFIX_BANK)
    urdu = rng.choice(URDU_SPRINKLES)
    base = (pre + q + suf + urdu).strip()
    if rng.random() < 0.05 and len(base) > 7:
        base = _swap_chars(base, rng)
    return base


# ---------------- session generator ----------------


def _load_faqs() -> list[dict]:
    p = HERE / "faqs.jsonl"
    out: list[dict] = []
    with p.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(json.loads(line))
    return out


def _session_id(faq_id: str, k: int) -> str:
    h = hashlib.md5(f"{faq_id}|{k}".encode()).hexdigest()[:10]
    return f"synth-{h}"


def synthesise(target_bytes: int, seed: int = 1) -> list[dict]:
    rng = random.Random(seed)
    faqs = _load_faqs()
    if not faqs:
        return []
    out: list[dict] = []
    total = 0
    # Round-robin over FAQs, generating a paraphrased session each pass.
    k = 0
    while total < target_bytes:
        faq = faqs[k % len(faqs)]
        k += 1
        q_para = paraphrase(faq["question"], rng)
        # Optional second user turn (follow-up).
        n_followups = 1 if rng.random() < 0.55 else 0
        turns = [
            {"role": "user", "text": q_para},
            {"role": "bot",  "text": faq["answer"]},
        ]
        for _ in range(n_followups):
            f_q = rng.choice(FOLLOWUP_TEMPLATES)
            f_a = rng.choice(FOLLOWUP_BOT_LINES)
            turns.append({"role": "user", "text": f_q})
            turns.append({"role": "bot",  "text": f_a})
        rec = {
            "session_id": _session_id(faq.get("id", str(k)), k),
            "specialty": faq["specialty"],
            "turns": turns,
            "synthetic": True,
            "source_faq_id": faq.get("id"),
        }
        out.append(rec)
        total += len(json.dumps(rec, ensure_ascii=False)) + 1
    return out


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--bytes", type=int, default=5_000_000,
                   help="target uncompressed size in bytes")
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--out", type=str,
                   default=str(HERE / "synth_chat_logs.jsonl"))
    args = p.parse_args()

    rows = synthesise(args.bytes, seed=args.seed)
    with open(args.out, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    size = Path(args.out).stat().st_size
    print(f"wrote {args.out}")
    print(f"  sessions     : {len(rows):,}")
    print(f"  size on disk : {size:,} bytes ({size / 1_000_000:.2f} MB)")


if __name__ == "__main__":
    main()
