"""Real-time auto-FAQ mining.

Closes the original project loop: chat traffic → candidate FAQs.

Flow
====
1. Every chat turn checks the retrieval confidence.
2. If the bucket is ``none`` (no good match), the user question goes
   into the per-specialty ``unmatched`` queue with its TF-IDF vector
   embedding cached.
3. Periodically (after N new unmatched questions, or on demand via the
   admin endpoint) we cluster the queue with our in-house K-Means.
4. Clusters of size ≥ ``min_cluster_size`` are written as
   *candidate FAQs* into the ``candidates`` collection. The
   representative question is the centroid-closest one; the proposed
   answer is generated by the seq2seq model if available, or left
   blank for the clinician to fill in.
5. Admin approves / edits / rejects through the existing admin
   dashboard. Approved candidates are inserted into ``faqs`` and live
   FAQ counts begin from the cluster size.

This is the same idea used in production systems like Intercom's
Resolution Bot and Drift's playbook miner — semantic deduplication of
incoming messages, with human review before publishing.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import numpy as np

from app.db import get_db
from app.myml.kmeans import KMeans
from app.myml.linalg import cosine_similarity
from app.myml.tfidf import TfidfVectorizer


_MIN_CLUSTER_SIZE = 3
_AUTO_RUN_EVERY = 5         # try clustering every N new unmatched turns
_MAX_QUEUE = 500            # cap the per-specialty queue
_SIMILARITY_THRESHOLD = 0.6  # near-duplicate question detection


@dataclass
class _Queue:
    questions: list[str] = field(default_factory=list)
    timestamps: list[datetime] = field(default_factory=list)
    runs_since_last_cluster: int = 0


_QUEUES: dict[str, _Queue] = {}
_VECTORISER: TfidfVectorizer | None = None


def _vectoriser() -> TfidfVectorizer:
    """Lazy-build a TF-IDF over the union of all queues."""
    global _VECTORISER
    if _VECTORISER is None:
        _VECTORISER = TfidfVectorizer(
            analyzer="word", ngram_range=(1, 2),
            min_df=1, sublinear_tf=True,
        )
    return _VECTORISER


async def enqueue_unmatched(specialty: str, question: str) -> dict:
    """Add an unmatched question to the per-specialty mining queue."""
    if not question or not question.strip():
        return {"queued": False, "reason": "empty"}
    q = _QUEUES.setdefault(specialty, _Queue())
    # Cap the queue.
    if len(q.questions) >= _MAX_QUEUE:
        q.questions.pop(0)
        q.timestamps.pop(0)
    q.questions.append(question.strip())
    q.timestamps.append(datetime.utcnow())
    q.runs_since_last_cluster += 1
    info: dict[str, Any] = {"queued": True, "queue_size": len(q.questions)}

    # Trigger clustering on threshold.
    if q.runs_since_last_cluster >= _AUTO_RUN_EVERY and len(q.questions) >= _MIN_CLUSTER_SIZE:
        q.runs_since_last_cluster = 0
        cresult = await _cluster_and_publish(specialty, q.questions)
        info["clustering"] = cresult
    return info


async def _cluster_and_publish(specialty: str,
                                questions: list[str]) -> dict:
    """K-Means over the queue; publish clusters of size >= min as
    candidate FAQs."""
    if len(questions) < _MIN_CLUSTER_SIZE:
        return {"clusters": 0, "candidates": 0}

    # Refit a vectoriser on the queue so the projection is local.
    vec = TfidfVectorizer(
        analyzer="word", ngram_range=(1, 2),
        min_df=1, sublinear_tf=True,
    )
    X = vec.fit_transform(questions)
    if X.shape[0] == 0 or X.shape[1] == 0:
        return {"clusters": 0, "candidates": 0}

    # k = ceil(N / 4) gives roughly 4-element clusters on average.
    import math
    k = max(2, math.ceil(len(questions) / 4))
    km = KMeans(n_clusters=k, n_init=4, random_state=0)
    labels = km.fit_predict(X)

    # Group by cluster.
    groups: dict[int, list[int]] = {}
    for i, lab in enumerate(labels):
        groups.setdefault(int(lab), []).append(i)

    db = get_db()
    candidates_added = 0
    now = datetime.utcnow()
    for cid, members in groups.items():
        if len(members) < _MIN_CLUSTER_SIZE:
            continue
        member_vecs = X[members]
        centroid = member_vecs.mean(axis=0)
        # Closest question to the centroid is the representative.
        sims = cosine_similarity(centroid[None, :], member_vecs).flatten()
        best = int(sims.argmax())
        canonical_q = questions[members[best]]

        # Generate a candidate answer with the seq2seq if available.
        candidate_answer = _generate_or_blank(canonical_q)

        cluster_key = f"auto-{specialty}-{abs(hash(canonical_q.lower())) % 10**10}"
        await db.faqs.update_one(
            {"specialty": specialty, "cluster_id": cluster_key},
            {"$set": {
                "specialty": specialty,
                "question": canonical_q,
                "answer": candidate_answer or "[clinician review needed]",
                "count": len(members),
                "approved": False,
                "rejected": False,
                "cluster_id": cluster_key,
                "auto_generated": True,
                "member_questions": [questions[i] for i in members],
                "updated_at": now,
            }},
            upsert=True,
        )
        candidates_added += 1
    return {"clusters": len(groups), "candidates": candidates_added}


def _generate_or_blank(question: str) -> str:
    """Use the seq2seq generator if a checkpoint is available, else
    return an empty string so the admin must fill it in by hand."""
    try:
        from app.services.generator import generate_answer
        text = generate_answer(question)
        if text and len(text.split()) >= 3:
            return text
    except Exception:
        pass
    return ""


async def queue_status() -> dict:
    return {
        spec: {
            "queue_size": len(q.questions),
            "runs_since_last_cluster": q.runs_since_last_cluster,
        }
        for spec, q in _QUEUES.items()
    }


async def force_cluster(specialty: str) -> dict:
    q = _QUEUES.get(specialty)
    if not q or len(q.questions) < _MIN_CLUSTER_SIZE:
        return {"clustered": False, "queue_size": len(q.questions) if q else 0}
    res = await _cluster_and_publish(specialty, q.questions)
    q.runs_since_last_cluster = 0
    return {"clustered": True, **res}


def looks_like_duplicate(question: str, faqs: list[dict],
                          threshold: float = _SIMILARITY_THRESHOLD) -> dict | None:
    """Cheap O(N) semantic dedup: is the user question already in the corpus?"""
    if not faqs or not question.strip():
        return None
    texts = [f.get("question", "") for f in faqs]
    vec = TfidfVectorizer(
        analyzer="word", ngram_range=(1, 2),
        min_df=1, sublinear_tf=True,
    )
    Xc = vec.fit_transform(texts + [question])
    sims = cosine_similarity(Xc[-1:], Xc[:-1]).flatten()
    best = int(sims.argmax())
    if sims[best] >= threshold:
        return {"faq": faqs[best], "similarity": float(round(sims[best], 3))}
    return None
